
-- 1 SELECT NOME e ANO
SELECT Nome,Ano FROM Filmes

-- 2 SELECT NOME E ANO EM ORDEM CRESCENTE
SELECT Nome,Ano,Duracao From Filmes ORDER BY Ano ASC

-- 3 SELECT FILME DE VOLTA PARA O FUTURO
SELECT * FROM Filmes WHERE Nome = 'De Volta para o Futuro'

-- 4 SELECT MOVIES RELEASED IN 1997
SELECT * FROM Filmes WHERE Ano = 1997

-- 5 SELECT MOVIES RELEASED AFTER 20s
SELECT * FROM Filmes WHERE Ano >= 2000

-- 6 SELECT MOVIES WITH DURATION BIGGER THAN 100 AND LESS AND 150 IN DESC ORDER
SELECT * FROM FILMES WHERE Duracao > 100 AND Duracao <150 ORDER BY Duracao ASC

-- 7 SEARCH THE QUANTITY OF MOVIES RELEASED IN THE YEAR GROUPING BY IT AND ORDERING IT BY THE DURATION IN DESC ORDER
SELECT * FROM Filmes SELECT ANO, COUNT(*) Quantidade FROM Filmes GROUP BY Ano ORDER BY Quantidade DESC

--8 SELECT MALE ACTORS RETURNING THE FIRST AND LAST NAME
SELECT * FROM Atores
SELECT PrimeiroNome,UltimoNome,Genero FROM Atores WHERE Genero = 'M'

--9 SELECT ACTORS OF FEMALE GENDER RETURNING THE FIRST NAME, LAST NAME AND ORDERED BY FIRSTNAME
SELECT PrimeiroNome,UltimoNome,Genero FROM Atores WHERE Genero = 'F' ORDER BY PrimeiroNome

--10 SELECT THE MOVIE NAME AND GENDER
SELECT * FROM Filmes
SELECT * FROM Generos
SELECT Filmes.Nome,Generos.Genero FROM Filmes INNER JOIN Generos ON Filmes.Id = Generos.Id
--11 SELECT ALL MOVIES WITH THE GENDER 'Mystery'
SELECT F.Nome, G.Genero FROM Filmes F INNER Join Generos G ON F.Id = G.Id WHERE G.Genero = 'Mistério'
 SELECT*FROM Atores
 SELECT * FROM Filmes
 SELECT * FROM ElencoFilme

 --12 SELECT THE MOVIE NAME, ITS ACTORS FIRST AND LAST NAME AND THEIR ROLE
 SELECT 
  Filmes.Nome,
  Atores.PrimeiroNome,
  Atores.UltimoNome,
  ElencoFilme.Papel 
  FROM Filmes INNER JOIN Atores ON Filmes.Id = Atores.Id  INNER JOIN ElencoFilme ON Atores.Id = ElencoFilme.Id